jobs:
  publish:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: pip install twine && twine upload
orbs:
  python: circleci/python@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - run: python --version
      - python/test:
          args: '--dev'
          pkg-manager: pipenv
          test-tool: pytest
      #- publish
# version: 2.1
# workflows:
#   ci:
#     jobs:
#       build:
#         docker:
#           - image: cimg/python:3.9.5
#         steps:
#           - checkout
#           - run: |
#               python --version
#               pip install pipenv
#               pipenv install
#               pipenv shell
#               pip install -e .
#               pytest .